# Repository settings for kf-component-library
# https://github.com/repository-settings/app

repository:
  # Repository description
  description: "kf components, shadcn/ui components. styles with kf-tailwind"

  # Repository homepage URL
  homepage: "https://www.npmjs.com/package/kf-component-library"

  # Repository topics/tags
  topics:
    - react
    - typescript
    - component-library
    - tailwindcss
    - radix-ui
    - shadcn-ui
    - ui-components
    - design-system
    - accessible
    - kf-components
    - vite
    - npm-package

  # Repository settings
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: false
  delete_branch_on_merge: false
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Branch protection rules
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "build"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        require_last_push_approval: false
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false

  - name: develop
    protection:
      required_status_checks:
        strict: false
        contexts:
          - "build"
      enforce_admins: true
      required_pull_request_reviews: null
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false
      required_linear_history: false
      dismiss_stale_reviews: false
