name: Enforce PR Source Branch

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  check-source-branch:
    name: Check PR Source Branch
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR source branch
        run: |
          echo "🔍 Checking PR source branch..."
          echo "Source branch: ${{ github.head_ref }}"
          echo "Target branch: ${{ github.base_ref }}"

          if [ "${{ github.base_ref }}" = "main" ] && [ "${{ github.head_ref }}" != "develop" ]; then
            echo ""
            echo "❌ ERROR: Pull requests to 'main' are only allowed from 'develop' branch"
            echo ""
            echo "Current source: ${{ github.head_ref }}"
            echo "Required source: develop"
            echo ""
            echo "Please follow the correct workflow:"
            echo "1. Merge your changes to 'develop' branch first"
            echo "2. Then create PR from develop → main"
            echo ""
            exit 1
          fi

          echo "✅ PR source branch is valid: ${{ github.head_ref }} → ${{ github.base_ref }}"
